activate:
	source venv/bin/activate
deactivate:
	deactivate
freeze:
	pip freeze > requirements.txt
install:
	pip install -r requirements.txt
run:
	docker-compose up
down:
	docker-compose down
build:
	docker-compose build
